config/routes.rb
V1::Application.routes.draw do

  resources :comments

  resources :users
	resources :images

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:index]

	root "welcome#index"
  match '/images/:id/like', :to=>'images#like', :via=>'get'
  match '/images/:id/unlike', :to=>'images#unlike', :via=>'get'
  
	match '/blog', :to=>'welcome#blog', :via=>'get'
	match '/home', :to=>'images#index', :via=>'get'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/image.rb
class Image < ActiveRecord::Base
	# after_initialize :defaults, unless: :persisted?
    before_save :default_values
    def default_values
        self.likes ||= 0
        self.likedby ||= ""
    end
    
    has_many :comments, :dependent => :destroy
	belongs_to :User
	default_scope -> { order('created_at DESC') }
	validates :title, presence: true
	has_attached_file :image, :styles => {:best_use => "800x600>",:medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	# validates :user_id, presence: true

	# private
	# 	def defaults
	# 		self.user_id = 1
	# 		self.save
	# 	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :like, :unlike]

  def index
    @images = Image.all
    @image = Image.new
  end

  def show
    @comment = Comment.new( :image => @image )
    @comment.commenter = current_user.id
  end

  def like
    if current_user.id.to_s != @image.user_id.to_s
        @a = User.find(@image.user_id)
        @b = @a.notification + "+#{current_user.id} LIKE #{@image.id}"
        @a.update_attributes(:notification => @b)
        @a.save
    end
    if @image.likes
      @image.likes += 1
      @image.likedby += "+#{current_user.id}"
    else
      @image.likes = 1
      @image.likedby = "#{current_user.id}"
    end
    @image.save
    redirect_to :back
  end

  def unlike
    @image.likes -= 1
    @image.likedby = (@image.likedby.split('+') - [current_user.id.to_s]).join('+')
    @image.save
    redirect_to :back
  end


  def new
    @image = Image.new
    # current_user.images.create()
    # @image.user_id = current_user.id
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    # current_user.images.create(image_params)
    @image.user_id = current_user.id
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.image = nil
    @image.save
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :image)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_comment.html.erb
<% @image.comments.each do |comment| %>
<div class="comment">
  
  <strong><i><%= h User.find(comment.commenter)[:name] %> :&nbsp;&nbsp;</i></strong>
  <%= comment.body %>
 
  <% if comment.commenter == current_user.id %><%= link_to 'Delete Comment', comment,
    {:confirm => 'Are you sure?',
    :method => :delete, :style => 'background-color:#FFFFFF;color:red;float:right;'} %>
  <% end %>
 <hr/>
</div>
<% end %>

app/views/images/_form.html.erb
<div  style="padding-left:100px;padding-right:100px; padding-top:50px;text-align:center">
<div class="well">

<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
      <span class="input-group-addon"> &nbsp; &nbsp; Title &nbsp; &nbsp; </span>
      <%= f.text_field :title, {class: "form-control"} %></div>
      <%= f.file_field :image %>
      <div class="well">
      <div style="padding-top:10px;"><%= f.submit ({class: "btn btn-success"}) %></div>
      </div>
  </div>

<% end %>
</div>
</div>

app/views/images/edit.html.erb
<div style="padding-left:200px;padding-right:200px;text-align:center;padding-top:80px;">
<div class="well">
<strong><%= @image.title %></strong>
<span style="float:right">

<%= link_to 'Delete Image', @image,
    {:confirm => 'Are you sure?',
    :method => :delete, :class=>"btn btn-danger"} %>

</span>
<hr/>

<%= image_tag @image.image.url(:medium) %>
</div>
</div>
<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div style="padding-left:50px;padding-right:50px;padding-top:5px;">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Upload Image</h3>
  </div>
  <div class="panel-body">
    <%= form_for(@image, :html => { :multipart => true, :class=>"navbar-form" }) do |f| %>
    <% if @image.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="input-group">
      <span class="input-group-addon"> &nbsp; &nbsp; Title &nbsp; &nbsp; </span>
      <%= f.text_field :title, {class: "form-control", placeholder: "Make it a catchy one."} %></div>
      <div class="well">
      <div><%= f.file_field :image %></div>
      <div style="padding-top:10px;"><%= f.submit ({class: "btn btn-success"}) %></div>
      </div>
    
<% end %>
</div>


</div>
</div>

<div style="padding-left:50px;">
  <%= link_to "View By Users", users_path, {:class=>"btn btn-warning"} %>
</div>
<div class="row" style = "padding-left:20px;padding-right:20px;padding-top:25px">
  <% @images.each do |image| %>
    <div class="col-md-4 col-md-4">
      <div class="thumbnail" style="text-align:center;">
        <h4><%= link_to "#{User.find(image.user_id).name}", "/users/#{image.user_id}", {style: ' color:#000000; background-color:#FFFFFF;'} %></h4>

        <%= image_tag image.image.url(:medium) %>
        <div class="caption">
          <p><a href= <%= "images/#{image.id}" %> class="btn btn-default" role="button">View Image</a> &nbsp; &nbsp; &nbsp; 
          <% if image.likes %>
          <%= "#{image.likes}" %>
          <% else %>
          0
          <% end %>
          <span class="glyphicon glyphicon-heart"></span>
          </p>      
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<% provide :title, @image.title %>

<div style="padding-left:50px;padding-right:50px;text-align:center;padding-top:10px;">
<div class="well">
<strong><%= @image.title %></strong><hr/>


<%= image_tag @image.image.url(:best_use) %><br>
<div style="padding-top:10px;text-align:left">
<%= link_to "#{User.find(@image.user_id).name}", users_path, {:class=>"btn btn-primary"} %>

<span style="float:right">
<% if @image.user_id == current_user.id.to_s %>
<%= link_to 'Edit', edit_image_path(@image), {:class=>"btn btn-success"} %>
<% end %>
</span>
</div>
</div>
</div>

<div style="padding-left:150px;padding-right:150px">
<div class="panel panel-default">
  <div class="panel-heading">
  <h3 class="panel-title">
    <span style="align-text:left"><%= @image.likes%>&nbsp;</span><span class="glyphicon glyphicon-heart"></span>&nbsp;&nbsp;

    <%if @image.likedby == nil || @image.likedby =='' || !(@image.likedby.split('+')).include?(current_user.id.to_s) %>
      <%= link_to "Like", "/images/#{@image.id}/like", {:method=>:get, :style=>"style: color:#000000; background-color:#FFFFFF;"} %>
    <% else %>
      <%= link_to "Unlike", "/images/#{@image.id}/unlike", {:method=>:get, :style=>"style: color:#000000; background-color:#FFFFFF;"}%>
    <% end %>

    <span style="display:block;float:right"><%= @image.comments.length %> comments</span>
  </h3>
  </div>
  <div class="panel-body" style="padding-left:20px;padding-right:20px">
  
  <div class="well">
  <%= render 'comment' %>
  </div>

  <div class = "well">
    <%= form_for @comment do |f| %>
    <%= f.hidden_field :image_id %>
      <div class="input-group">
      <span class="input-group-addon"> &nbsp; &nbsp; Views: &nbsp; &nbsp; </span>
      <%= f.text_area :body, {class: "form-control"} %></div>
      
      <div style="text-align:right;padding-top:10px;"><%= f.submit ({class: "btn btn-success"}) %></div>
      
<% end %>
</div>


</div>
</div>
</div>